export XSECURELOCK_AUTH_WARNING_COLOR=#fecf6a
export XSECURELOCK_SAVER=saver_mplayer
export XSECURELOCK_AUTH_BACKGROUND_COLOR=#019875
export XSECURELOCK_FONT="SFNS Display"
export XSECURELOCK_LIST_VIDEOS_COMMAND="find ~/Vidéos -type f"
